= Demo for various runtime options for Jakarta EE applications

The application uses a simple REST/CDI/JPA stack:

* `PersonResource` exposes a simple CRUD api with the path `person`. +
As an example `curl localhost:8080/person` will retrieve some demo data in JSON. +
(For conveniance, test data are inserted into the database on first call)

* `Person` ist a simple JPA entity used for the demo data.

* `PersonRepository` loads and stores `Person` entries from/into the default datasource (using an in memory H2 db).

* A second REST resource is `HelloResource` publishing `Hello!` as plain text with path `hello`.

The maven POM file defines a default goal of `package` and a final name of `jee-runtimes-demo`. Therefore `mvn` will build a WAR file `target/jee-runtimes-demo.war` containing the application.

== Standard JEE server deployment

The WAR file can be deployed in any Jakarta EE 8 server, e. g. WildFly 24.

== WildFly Bootable JAR

The project defines the maven profile `wildfly-bootable-jar`. If it's activated for building (i. e. `mvn -Pwildfly-bootable-jar`) an additional JAR file is built: `target/jee-runtimes-demo-bootable.jar` (*). It is a hollow JAR containing a WildFly server customized to just the extension needed (`jaxrs`, `cdi`, `jpa`, `h2-default-datasource`). The application can be started by

`java -jar target/jee-runtimes-demo-bootable.jar --deployment=target/jee-runtimes-demo.war`

The WildFly JAR plugin used for building the hollow JAR can also start the application in development mode:

`mvn -Pwildfly-bootable-jar wildfly-jar:dev-watch`

In this mode the server watches the program sources and hot reloads the application if something changes.

(*) Due to a bug in the plugin, the hollow JAR cannot be renamed into e.g. `wildfly-bootable.jar`, because the JAR wouldn't be found by the development mode runner.

== Payara Micro

If you enable the maven profile `payara-micro` (i. e. `mvn -Ppayara-micro`), Payara Micro is downloaded into `target/payara-micro.jar`. It's a Jakarta EE Web Profile server including some extensions. The application can be started by

`java -jar target/payara-micro.jar target/jee-runtimes-demo.war`

== Quarkus

The Quarkus build can be run with `mvn -Pquarkus`. It results in a directory `target\quarkus-app` containing the runner JAR `quarkus-run.jar` and subdirectories for application and runtime infrastructure. The application can be started by

`java -jar target/quarkus-app/quarkus-run.jar`

The Quarkus plugin used for building can also start the application in development mode:

`mvn -Pquarkus quarkus:dev`

In this mode the runtime watches the program sources and hot reloads the application if something changes.

It should be noted, that the project setup for quarkus in `pom.xml` is more complicated than it would be in normal projects: We wanted to have exactly the same source for both classical JEE environments and quarkus. This made it necessary to swich the project packaging from `war` for JEE to `jar` for Quarkus with the help of the maven property `packaging.type`, which can be done only, if the Quarkus plugin is configured with `quarkus.bootstrap.effective-model-builder` as `true`. The drawback of using the effective POM is a slower build, so you would not enable this option in normal projects.